type "1. CDK_codes.sql" > whole_script.sql
type "2. creatinine.sql" >> whole_script.sql
type "3. height.sql" >> whole_script.sql
type "4. eGFR.sql" >> whole_script.sql
type "5.0 transplant.sql" >> whole_script.sql
type "5.1 dialysis.sql" >> whole_script.sql
type "5.2 Other_Acute.sql" >> whole_script.sql
type "5.3 AKD.sql" >> whole_script.sql
type "5.4 CKD.sql" >> whole_script.sql
type "5.5 Other_KD.sql" >> whole_script.sql
type "6.0 Phenotype.sql" >> whole_script.sql
